-- Insert all 15 Spanish FAQ translations
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/sdpmwelfkseuhlhgatsc/sql/new

INSERT INTO faq (slug, question, answer_markdown, category, priority, language) VALUES
('what-is-cannabis-club', '¿Qué es un club social de cannabis?', 'Un club social de cannabis (CSC) es una asociación cultural privada sin ánimo de lucro donde los miembros pueden consumir cannabis legalmente en un entorno seguro y controlado. Estos clubes operan bajo la ley española de asociaciones y no son negocios comerciales. Existen para proporcionar a los miembros una alternativa responsable al mercado ilegal.', 'basics', 10, 'es'),

('are-clubs-legal-madrid', '¿Son legales los clubes de cannabis en Madrid?', 'Los clubes sociales de cannabis existen en un área legal gris en España. Aunque el consumo personal de cannabis y el cultivo para uso privado están despenalizados, estos clubes operan como asociaciones privadas bajo el derecho a la libertad de asociación. No son explícitamente legales ni ilegales, pero deben seguir pautas estrictas para evitar procesamientos. Los clubes deben ser verdaderamente privados, sin ánimo de lucro y servir solo a miembros registrados.', 'law', 20, 'es'),

('can-tourists-join', '¿Pueden los turistas unirse a un club de cannabis en España?', 'Sí, los turistas pueden unirse a clubes sociales de cannabis en Madrid, aunque el proceso varía según el club. Normalmente necesitas un DNI o pasaporte válido, debes ser mayor de 18 años (o 21 en algunos clubes) y requieres una invitación de un miembro existente. Algunos clubes son más amigables con los turistas que otros. Es importante contactar con los clubes con antelación para entender sus requisitos específicos de membresía.', 'membership', 30, 'es'),

('membership-requirements', '¿Cuáles son los requisitos para convertirse en miembro?', 'Los requisitos varían según el club pero generalmente incluyen: ser mayor de 18 o 21 años, tener un DNI o pasaporte válido, recibir una invitación de un miembro actual, completar una solicitud de membresía y pagar una cuota de socio. Algunos clubes requieren prueba de residencia en España, mientras que otros aceptan turistas. Todos los miembros deben aceptar las reglas y regulaciones del club sobre uso responsable.', 'membership', 40, 'es'),

('clubs-vs-dispensaries', '¿En qué se diferencian los clubes de cannabis de los dispensarios?', 'Los clubes de cannabis son fundamentalmente diferentes de los dispensarios comerciales. Los clubes son asociaciones privadas sin ánimo de lucro donde los miembros cultivan o compran colectivamente cannabis para consumo personal. No hay "compra" o "venta" - los miembros contribuyen a los costes y reciben su parte del cannabis del colectivo. Los dispensarios, por el contrario, son negocios comerciales que venden productos de cannabis a clientes. Esta distinción es crucial para entender cómo operan legalmente los clubes en España.', 'basics', 50, 'es'),

('public-consumption-legal', '¿Es legal consumir cannabis en público en España?', 'No. Aunque el uso personal está despenalizado en España, consumir cannabis en espacios públicos es ilegal y puede resultar en multas. El consumo de cannabis solo está permitido en espacios privados, incluidos los clubes sociales de cannabis autorizados. Por esto existen los clubes - para proporcionar a los miembros un espacio legal y privado para el consumo. El consumo público sigue sujeto a sanciones administrativas.', 'law', 60, 'es'),

('what-to-bring-joining', '¿Qué debo llevar al unirme a un club?', 'Al visitar un club de cannabis por primera vez, lleva un DNI o pasaporte válido emitido por el gobierno, efectivo para las cuotas de membresía (la mayoría de los clubes no aceptan tarjetas), e información de contacto de tu referencia/invitación si es requerida. También se recomienda llevar una mente abierta y respeto por las reglas del club. Algunos clubes pueden solicitar documentación adicional dependiendo de sus requisitos específicos.', 'membership', 70, 'es'),

('clubs-safe-regulated', '¿Son seguros y regulados los clubes de cannabis?', 'Los clubes de cannabis reputados priorizan la seguridad de los miembros y siguen prácticas responsables, aunque no están oficialmente regulados como establecimientos comerciales. Los clubes de calidad analizan su cannabis para detectar contaminantes, mantienen instalaciones limpias, capacitan al personal en reducción de daños y crean reglas para prevenir abusos. Sin embargo, el nivel de profesionalismo varía entre clubes. Esta guía destaca clubes verificados conocidos por mantener altos estándares de seguridad y calidad.', 'safety', 80, 'es'),

('membership-cost', '¿Cuánto cuesta la membresía en un club de cannabis?', 'Las cuotas de membresía varían significativamente entre clubes. La membresía anual típica oscila entre €20 y €50, con algunos clubes premium cobrando hasta €100. La mayoría de los clubes también requieren una cuota de registro inicial. Más allá de la membresía, contribuirás al coste colectivo del cannabis según tu consumo. Los costes totales dependen del uso pero son generalmente comparables o inferiores a los precios del mercado ilegal, con los beneficios añadidos de garantía de calidad, seguridad y legalidad.', 'membership', 90, 'es'),

('club-atmosphere', '¿Cómo es el ambiente en los clubes de cannabis?', 'Los clubes de cannabis de Madrid varían ampliamente en ambiente. Algunos se asemejan a salones modernos con sofás cómodos y música ambiente, mientras que otros tienen más de bar social con juegos y eventos comunitarios. Los clubes premium pueden ofrecer ambientes elegantes tipo lounge con asientos de alta gama. Todos los clubes priorizan la discreción, la limpieza y crear un espacio relajado donde los miembros puedan socializar o disfrutar del cannabis en privado. La mayoría tienen ventilación adecuada, áreas de fumadores y no fumadores, y normas estrictas sobre conducta.', 'basics', 100, 'es'),

('products-available', '¿Qué productos están disponibles en los clubes?', 'Los clubes de cannabis de Madrid típicamente ofrecen una variedad de flores de cannabis (cogollos) con diferentes cepas, niveles de THC y perfiles de terpenos. Muchos clubes también proporcionan concentrados, hachís y productos comestibles. La disponibilidad varía según el club - algunos ofrecen 10-15 cepas, mientras que clubes más grandes pueden tener 30-50 opciones. Los productos de calidad generalmente incluyen información sobre cepa, potencia y efectos. Algunos clubes premium ofrecen genéticas exclusivas o productos orgánicos certificados.', 'products', 110, 'es'),

('visiting-multiple-clubs', '¿Puedo visitar múltiples clubes?', 'Sí, puedes unirte y visitar múltiples clubes de cannabis en Madrid. Cada club requiere su propia membresía y cuota, pero no hay restricciones legales sobre pertenecer a varios clubes. Muchos entusiastas del cannabis se unen a 2-3 clubes para experimentar diferentes atmósferas, selecciones de productos y comunidades. Sin embargo, ten en cuenta que cada membresía tiene su propio coste anual, y debes respetar las reglas de cada club individual.', 'membership', 120, 'es'),

('cannabis-quality-testing', '¿Se analizan la calidad y seguridad del cannabis?', 'Los clubes reputados de cannabis realizan análisis de laboratorio de su cannabis para garantizar seguridad y calidad. Los análisis típicamente verifican niveles de cannabinoides (THC, CBD), contaminantes como pesticidas, metales pesados y moho, y en algunos casos perfiles de terpenos. Sin embargo, los análisis no son legalmente obligatorios, por lo que las prácticas varían. Los clubes de alta calidad generalmente muestran resultados de análisis y mantienen documentación de todas las fuentes de cannabis. Al elegir un club, pregunta sobre sus procedimientos de análisis.', 'safety', 130, 'es'),

('bringing-cannabis-home', '¿Puedo llevar cannabis de vuelta a mi país de origen?', 'No. Es ilegal transportar cannabis a través de fronteras internacionales, independientemente de las leyes locales en España o tu país de origen. El cannabis debe permanecer dentro de España y solo puede ser consumido en espacios privados (tu alojamiento o dentro de clubes). Los aeropuertos y fronteras tienen controles de seguridad estrictos. Cruzar fronteras con cannabis puede resultar en cargos criminales graves, incluida la cárcel. Solo consume y desecha tu cannabis dentro de España antes de viajar.', 'law', 140, 'es'),

('club-etiquette', '¿Cuáles son las reglas de etiqueta en los clubes?', 'La etiqueta básica en los clubes de cannabis incluye: respetar a otros miembros y su espacio personal, mantener niveles de ruido razonables, no fotografiar sin permiso (la mayoría de los clubes prohíben fotos), no traer visitantes no miembros, seguir las reglas de fumar del club (algunas áreas pueden ser solo para vaporizar), limpiar tu espacio, y nunca compartir o revender cannabis fuera del club. Los clubes esperan consumo responsable - evita el consumo excesivo. Siempre pregunta al personal si no estás seguro sobre las reglas.', 'etiquette', 150, 'es');

-- Verify the inserts
SELECT 'Spanish FAQs inserted successfully!' as result, COUNT(*) as total_spanish_faqs 
FROM faq 
WHERE language = 'es';
