INSERT INTO public.clubs (
  name,
  slug,
  description,
  summary,
  address,
  district,
  city,
  country,
  postal_code,
  status,
  is_tourist_friendly,
  is_verified,
  is_featured,
  rating_editorial,
  rating_safety,
  rating_ambience,
  rating_location,
  languages,
  main_image_url,
  timetable,
  google_place_id,
  website_url,
  instagram_url,
  seo_title,
  seo_description
) VALUES (
  'Meltz Club Social Madrid',
  'meltz-club-social-madrid',
  'Meltz Club Social Madrid is a welcoming cannabis social club located in the Fuencarral-El Pardo district near Barrio del Pilar. Known for its relaxed atmosphere and friendly community, Meltz offers a comfortable space for members to enjoy cannabis in a safe and legal private setting. The club features extended hours and welcomes both Spanish and English speakers, making it accessible for international visitors.',
  'Modern cannabis social club in Fuencarral-El Pardo with welcoming atmosphere and bilingual staff.',
  'Av. de Monforte de Lemos, 89, Fuencarral-El Pardo, 28029 Madrid, España',
  'Fuencarral-El Pardo',
  'Madrid',
  'ES',
  '28029',
  'active',
  true,
  true,
  false,
  4.2,
  4.3,
  4.1,
  3.9,
  ARRAY['es', 'en'],
  '/images/clubs/club-wellness.jpg',
  '{"monday": {"open": "10:00", "close": "22:00"}, "tuesday": {"open": "10:00", "close": "22:00"}, "wednesday": {"open": "10:00", "close": "22:00"}, "thursday": {"open": "11:00", "close": "23:00"}, "friday": {"open": "11:00", "close": "23:00"}, "saturday": {"open": "11:00", "close": "23:00"}, "sunday": {"open": "10:00", "close": "22:00"}}'::jsonb,
  'ChIJp-gzy_0pQg0RG_e7QPbpCtk',
  'https://www.meltzmadrid.com',
  'https://instagram.com/meltzclub',
  'Meltz Club Social Madrid | Cannabis Club Fuencarral-El Pardo',
  'Join Meltz Club Social Madrid in Fuencarral-El Pardo. Welcoming cannabis social club near Barrio del Pilar with bilingual staff. Open 10:00-23:00.'
)
ON CONFLICT (slug) DO UPDATE SET
  google_place_id = EXCLUDED.google_place_id,
  address = EXCLUDED.address,
  postal_code = EXCLUDED.postal_code,
  timetable = EXCLUDED.timetable,
  website_url = EXCLUDED.website_url,
  instagram_url = EXCLUDED.instagram_url,
  languages = EXCLUDED.languages,
  is_verified = EXCLUDED.is_verified,
  updated_at = now();