-- Add 4 new verified clubs with Google Place IDs
INSERT INTO clubs (
  name, slug, description, summary, address, postal_code, district, city, country, 
  status, is_featured, is_tourist_friendly, is_verified, 
  rating_editorial, rating_safety, rating_ambience, rating_location, 
  languages, main_image_url, timetable, google_place_id, 
  website_url, whatsapp_number, seo_title, seo_description
) VALUES

-- Club 1: Genetics Social Club Madrid
(
  'Genetics Social Club Madrid',
  'genetics-social-club-madrid',
  'Genetics Social Club Madrid is a premier cannabis social club located in the heart of Chamberí on Calle de Galileo. Known for their exceptional genetic selection and knowledgeable staff, the club offers a welcoming atmosphere for both locals and tourists. With extended hours until midnight, it''s perfect for evening relaxation after exploring Madrid.',
  'Premium cannabis social club in Chamberí with exceptional genetics and extended hours until midnight.',
  'C. de Galileo, 47',
  '28015',
  'Chamberí',
  'Madrid',
  'ES',
  'active',
  false,
  true,
  true,
  4.4,
  4.5,
  4.3,
  4.6,
  ARRAY['es', 'en'],
  '/images/clubs/club-greenhouse.jpg',
  '{"monday": {"open": "11:00", "close": "00:00"}, "tuesday": {"open": "11:00", "close": "00:00"}, "wednesday": {"open": "11:00", "close": "00:00"}, "thursday": {"open": "11:00", "close": "00:00"}, "friday": {"open": "11:00", "close": "00:00"}, "saturday": {"open": "11:00", "close": "00:00"}, "sunday": {"open": "11:00", "close": "00:00"}}'::jsonb,
  'ChIJje_5Y6ApQg0RUMTQvjL3sa4',
  'https://weedmadridguide.com',
  '+34697696394',
  'Genetics Social Club Madrid | Premium Cannabis Club Chamberí',
  'Visit Genetics Social Club Madrid in Chamberí. Premium cannabis genetics, welcoming atmosphere, open daily until midnight. Tourist-friendly with English-speaking staff.'
),

-- Club 2: Lunga Social Club Madrid
(
  'Lunga Social Club Madrid',
  'lunga-social-club-madrid',
  'Lunga Social Club Madrid offers a relaxed and authentic cannabis experience on Calle de Galileo in Chamberí. This established club is known for its friendly community atmosphere and quality selection. With convenient hours from 10 AM to 11 PM daily, it caters to both early risers and evening visitors seeking a genuine Madrid cannabis club experience.',
  'Authentic cannabis social club in Chamberí with a friendly community atmosphere and quality selection.',
  'C. de Galileo, 99',
  '28015',
  'Chamberí',
  'Madrid',
  'ES',
  'active',
  false,
  true,
  true,
  4.2,
  4.4,
  4.3,
  4.5,
  ARRAY['es', 'en'],
  '/images/clubs/club-wellness.jpg',
  '{"monday": {"open": "10:00", "close": "23:00"}, "tuesday": {"open": "10:00", "close": "23:00"}, "wednesday": {"open": "10:00", "close": "23:00"}, "thursday": {"open": "10:00", "close": "23:00"}, "friday": {"open": "10:00", "close": "23:00"}, "saturday": {"open": "10:00", "close": "23:00"}, "sunday": {"open": "10:00", "close": "23:00"}}'::jsonb,
  'ChIJ7UP0QQApQg0RSqQ7uw9NdEA',
  'https://lungamadrid.com',
  NULL,
  'Lunga Social Club Madrid | Cannabis Club Chamberí District',
  'Discover Lunga Social Club Madrid in Chamberí. Friendly community atmosphere, quality cannabis selection, open 10 AM - 11 PM daily. Welcoming to tourists.'
),

-- Club 3: Madrid Relax Social Club
(
  'Madrid Relax Social Club',
  'madrid-relax-social-club',
  'Madrid Relax Social Club is located in the vibrant Malasaña neighborhood on Calle de la Palma. True to its name, this club focuses on creating a stress-free, relaxing environment for members. The intimate setting and carefully curated selection make it a favorite among those seeking a calm cannabis experience in the heart of Madrid''s most artistic district.',
  'Relaxing cannabis club in Malasaña offering a calm, stress-free atmosphere in Madrid''s artistic heart.',
  'C. de la Palma, 13',
  '28004',
  'Centro',
  'Madrid',
  'ES',
  'active',
  false,
  true,
  true,
  4.3,
  4.5,
  4.6,
  4.7,
  ARRAY['es', 'en'],
  '/images/clubs/club-malasana.jpg',
  '{"monday": {"open": "11:00", "close": "22:30"}, "tuesday": {"open": "11:00", "close": "22:30"}, "wednesday": {"open": "11:00", "close": "22:30"}, "thursday": {"open": "11:00", "close": "22:30"}, "friday": {"open": "11:00", "close": "22:30"}, "saturday": {"open": "11:00", "close": "22:30"}, "sunday": {"open": "11:00", "close": "22:30"}}'::jsonb,
  'ChIJJ71WbQApQg0RdILyhXyBPbk',
  'https://madridrelax.com',
  '+34614271233',
  'Madrid Relax Social Club | Cannabis Club Malasaña Centro',
  'Visit Madrid Relax Social Club in Malasaña. Calm, relaxing atmosphere in Madrid''s artistic district. Open daily 11 AM - 10:30 PM. Tourist-friendly.'
),

-- Club 4: Cannabis Store Amsterdam Madrid
(
  'Cannabis Store Amsterdam Madrid',
  'cannabis-store-amsterdam-madrid',
  'Cannabis Store Amsterdam Madrid brings Dutch-inspired cannabis culture to the heart of Sol on Calle de la Montera. This centrally located club offers an Amsterdam-style experience with a diverse selection and professional service. Its prime location near Puerta del Sol makes it easily accessible for tourists staying in central Madrid.',
  'Amsterdam-style cannabis club in Sol with Dutch-inspired atmosphere and prime central location.',
  'C. de la Montera, 21',
  '28013',
  'Centro',
  'Madrid',
  'ES',
  'active',
  true,
  true,
  true,
  4.5,
  4.6,
  4.4,
  4.9,
  ARRAY['es', 'en', 'nl'],
  '/images/clubs/club-granvia.jpg',
  '{"monday": {"open": "10:30", "close": "22:00"}, "tuesday": {"open": "10:30", "close": "22:00"}, "wednesday": {"open": "10:30", "close": "22:00"}, "thursday": {"open": "10:30", "close": "22:00"}, "friday": {"open": "10:30", "close": "22:00"}, "saturday": {"open": "10:30", "close": "22:00"}, "sunday": {"open": "10:30", "close": "22:00"}}'::jsonb,
  'ChIJRZ69kGcpQg0R_vPfDA0mLrk',
  'https://cannabisstoreamsterdam.com',
  '+34912854667',
  'Cannabis Store Amsterdam Madrid | Dutch-Style Club Sol Centro',
  'Experience Cannabis Store Amsterdam Madrid near Puerta del Sol. Amsterdam-style atmosphere, prime central location, open 10:30 AM - 10 PM daily. Tourist favorite.'
);