// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdpmwelfkseuhlhgatsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkcG13ZWxma3NldWhsaGdhdHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3OTU5NzUsImV4cCI6MjA3ODM3MTk3NX0.MkYa4jNxLAbYQBZqxJIezn50uuipLaZHKm3Ls2ONjpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});